# ------------------------------------------------------
# 配置指南: https://github.com/Exisi/hexo-theme-node-tree
# 你可以从指南中获得更详细的说明
#
# Guide: https://github.com/Exisi/hexo-theme-node-tree
# You can get more detailed help from the guide
#------------------------------------------------------

#---------------------------
# 主题配置
# Theme Configuration
#---------------------------

#------------------------------------------------------
# 用于浏览器标签的图标
# Icon for browser tab
#------------------------------------------------------
favicon:
  light: /favicon-white.ico
  dark: /favicon.ico

#------------------------------------------------------
# 自定义 CSS 和 JS
# Custom CSS and JS
#------------------------------------------------------
custom:
  css:
    # css 文件路径列表
    # List of css file
    path:
  js:
    # 只在初次页面加载的脚本
    # The script that will be loaded only once when the page is loaded.
    base:
      # 是否异步加载
      # Whether to load async
      async: false
      # js文件路径列表
      # List of js file
      path:
    # 页面更新时将会重新加载的脚本
    # The script that will be reloaded when the page is change.
    reload:
      # 是否异步加载
      # Whether to load async
      async: true
      # js文件路径列表
      # List of js file
      path:

#------------------------------------------------------
# 标题菜单配置
# Header menu Settings
#------------------------------------------------------
header:
  # 是否启用标签菜单
  # Enable tag menu
  tag:
    enable: true
  # 是否启用分类菜单
  # Enable category menu
  category:
    enable: true
  # 是否启用 Github 菜单
  # Enable github menu
  github:
    enable: true
    url: ''
  # 是否启用关于菜单
  # Enable about menu
  about:
    enable: true
  # 是否启用黑暗模式
  # Enable dark model menu
  darkMode:
    enable: true

#------------------------------------------------------
# 侧边栏配置
# sidebar Settings
#------------------------------------------------------
sidebar:
  # 文章标题使用标题或文件名，如果未定义，默认为 false（使用文件名）
  # Post title use title or filename, If not defined, default is false (filename).
  usePostTitle: false
  search:
    # 如果未定义，默认为 google。设置引擎为
    # If not defined, default is google. Set engines as
    # https://www.baidu.com/s?wd=
    # https://www.google.com/search?q=
    engine: https://www.google.com/search?q=

#------------------------------------------------------
# 代码块的增强配置
# Enhancements to code blocks
#------------------------------------------------------
code:
  # 代码高亮
  # Code highlight
  highlight:
    highlightcss:
      # 在链接中挑选样式填入
      # Select a style in the link
      # See: https://highlightjs.org/static/demo/
      style: "tokyo-night-dark"
    prismcss:
      # 在链接中挑选样式填入
      # Select a style in the link
      # See: https://github.com/PrismJS/prism-themes?#available-themes
      style: "prism"
  # 代码复制按钮
  # Code copy button
  copyBtn:
    # 是否开启复制代码的按钮
    # Enable copy code button
    enable: true

#------------------------------------------------------
# 是否启用文章版权
# Enable the post copyright
#------------------------------------------------------
post:
  # 版权声明，会显示在每篇文章的结尾
  # Copyright, will be displayed at the end of each post
  copyright:
    enable: true
    # 知识共享许可协议
    # CreativeCommons license
    # See: https://creativecommons.org/share-your-work/cclicenses/
    # Options: BY | BY-SA | BY-ND | BY-NC | BY-NC-SA | BY-NC-ND | ZERO
    license: 'BY'
    # 显示作者
    # Show author
    author:
      enable: true
    # 显示发布日期
    # Show post date
    postDate:
      enable: true
      format: "LL"
    # 显示更新日期
    # Show update date
    updateDate:
      enable: false
      format: "LL"

#------------------------------------------------------
# 页脚配置
# Footer Settings
#------------------------------------------------------
footer:
  # 页脚第二行文字的 HTML，建议保留链接，用于向更多人推广本主题
  # HTML of the first line of the footer, it is recommended to keep the link to promote this theme to more people
  content: '
    <div>
      Theme
      <a href="https://github.com/Exisi/hexo-theme-node-tree"	target="_blank">Node-Tree</a>
      Powered by
      <a href="https://hexo.io" target="_blank">Hexo</a>
    </div>
  '

  # 版权声明，会显示在每个界面的结尾
  # Copyright, will be displayed at the end of each page
  copyright:
    enable: true
    url: ''
    baseYear: 2024
  # 展示网站的 PV、UV 统计数
  # Display website PV and UV statistics
  statistics:
    # Vercount 是一个基于 NextJS 和 Redis 的高效网站计数器。支持自部署
    # Vercount is an efficient website counter based on NextJS and Redis. Support self-deployment
    # see: https://vercount.one/
    vercount:
      enable: true
      src: https://cn.vercount.one/js

#------------------------------------------------------
# 文章评论，支持 giscus
# Post comment, support giscus
# see: https://giscus.app/
#------------------------------------------------------
comment:
  # 基于 GitHub Discussions
  # Based on GitHub Discussions, similar to Utterances
  # See: https://giscus.app/
  giscus:
    enable: false
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    reactions_enabled:
    emit_metadata:
    input_position:
    theme:

#------------------------------------------------------
# 是否启用网站分析，支持谷歌和百度分析
# Enable Website Analytics, Supporting Google and Baidu Analytics
#------------------------------------------------------
analytics:
  # 百度统计的 Key，值需要获取下方链接中 `hm.js?` 后边的字符串
  # Baidu analytics, get the string behind `hm.js?`
  # See: https://tongji.baidu.com/
  baidu:
    enable: false
    hm: ''
  # Google Analytics 4 的媒体资源 ID
  # Google Analytics 4 MEASUREMENT_ID
  # See: https://support.google.com/analytics/answer/9744165#zippy=%2Cin-this-article
  google:
    enable: false
    id: ''